import "../styles/globals.scss";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import SupportPanel from "../components/navigation-bar/SupportPanel";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div style={{ display: "flex", flexDirection: "column", minHeight: "100vh", backgroundColor: "rgba(0, 0, 0, 0.85)" }}>
          <Header />
          <SupportPanel />
          <main className="wrapper" style={{ flex: 1 }}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
